### ISSUE TITLE
I'd like to access it and ask some questions

### ISSUE THREAD

**Issue by Ives-code** [Liberty-Chain/LibertyChainGUI#1]
1

**Comment by Ives-code** [comment]
In addition, can you leave an official communication address

**Comment by 864861699** [comment]
> 1. Where is your official website? Can I send a white paper to any address?
> 2. I read the tutorial only for windows. Is there a tutorial for Linux? The windows tutorial is more suitable for users with a small number of machines. If the number of machines is large, the operation of Linux will be easier

**Comment by Ives-code** [comment]
1
